### PR TITLE
CI: Get Linux / OSX builds green

### PR DESCRIPTION
**Pull request by bryphe**

### CODE REVIEW

**Comment by bryphe** [comment]
Sorry for the noise!

**Comment by mattleibow** [comment]
No prob. What were you trying to do? Maybe we can do something to help?

**Comment by bryphe** [comment]
Hey @mattleibow ! 

We're working on OCaml / ReasonML bindings for Skia - just getting it hooked up into our build system. I made the PR against the wrong base fork 😬 

But since you're here, just wanted to say thank you for the work you and your team have done to build out the C API - we've been using that as our integration point for the OCaml / ReasonML FFI and it's been very helpful! 

We're looking forward to picking up the latest upstream in https://github.com/mono/skia/pull/64

Cheers and apologies again for the noise-

**Comment by mattleibow** [comment]
No problem. Feel free to open any issues if you need some member and it is missing. Then we can add it and you don't have to worry about maintaining your fork just to add members and things.

**Comment by manu-unter** [comment]
That's great to hear, @mattleibow! Maybe we can reintegrate our code and config changes again at some point when we made sure we have everything we need on all our supported platforms.

We will probably need to keep one separate layer for packing and publishing skia into npm for usage with esy, but that layer doesn't need to contain all the source as well. It might as well be a git submodule.

FWIW, the changes we made are mostly just config adaptations and a few fixes for errors that our dynamically linking compiler setup complained about. No new functionality so far - you did a great job with those bindings 👏

**Comment by mattleibow** [comment]
I saw some code changes. You can submit a PR for that as well. I have a good few compilers that seem to be fine with what we have. If your compilers are more picky, then do a PR and we can see if all our compilers are happy. If they are, then we can merge and you just need to worry about configuration.

**Pull request closed without merging**
