### PR TITLE
Added sk_canvas_draw_round_rect, sk_path_transform, sk_path_clone

### PR DESCRIPTION
**Pull request by kekekeks**

### CODE REVIEW

**Comment by kekekeks** [comment]
See https://github.com/mono/SkiaSharp/pull/63

**Comment by mattleibow** [comment]
Thanks for this @kekekeks ! Skia is moving along, and gaining APIs.
I was just wondering if you could move those new methods into the newly-created files instead of Google's files. 

https://github.com/mono/skia/tree/xamarin-mobile-bindings/include/c/xamarin
https://github.com/mono/skia/tree/xamarin-mobile-bindings/src/c/xamarin

I have just moved all the Xamarin-and-Community-created APIs into the files under the `xamarin` folder. This is to make merges from upstream much easier. And, instead of having a monster file `sk_surface.cpp` that has everything, I have split it up into several files - because we are cool like that 😄 

This is still m49 from Google, but in order to reduce time correcting merge issues, these changes will help future updates go much more smoothly. In fact, I was able to merge m50 (which I hope to get out vey soon) without any issues whatsoever: https://github.com/mono/skia/tree/xamarin-m50-update

m51 is still a bit rough, as Google is playing create-merge-conflicts with us: https://github.com/google/skia/compare/chrome/m51...chrome/m50. But, that won't stop us 😉

**Comment by kekekeks** [comment]
@mattleibow updated

**Comment by mattleibow** [comment]
@kekekeks Thanks!

**Pull request merged**
